[package]
name = "wrapped2d"
version = "0.2.5"
authors = ["Thomas Koehler <basta.t.k+git@gmail.com>"]

description = "Rust binding for Box2D"
documentation = "https://bastacyclop.github.io/rust_box2d/wrapped2d/"
repository = "https://github.com/Bastacyclop/rust_box2d.git"
readme = "README.md"
keywords = ["physics", "binding", "bindings", "box2d"]
license = "zlib-acknowledgement"

build = "build_frontend.rs"

[features]
default = ["nalgebra", "cgmath"]

[build-dependencies]
gcc = "0.3"

[dependencies]
libc = "0.2"
vec_map = "0.6"
bitflags = "0.6"

[dependencies.nalgebra]
version = "0.8"
optional = true

[dependencies.cgmath]
version = "0.9"
optional = true
